MODEL:
  TYPE: pjs
  NAME: hisfrag20_patch16_224
  DROP_PATH_RATE: 0.1
  NUM_CLASSES: 1
  PJS:
    EMBED_DIM: 1024
    PATCH_SIZE: 16
    DEPTH: 12
    C_DEPTH: 12
    NUM_HEADS: 16
DATA:
  DATASET: hisfrag20
  IMG_SIZE: 224
